const keysColl = [
    [
        { key: 'Backquote', value: '`' },
        { key: '1', value: 1 },
        { key: '2', value: 2 },
        { key: '3', value: 3 },
        { key: '4', value: 4 },
        { key: '5', value: 5 },
        { key: '6', value: 6 },
        { key: '7', value: 7 },
        { key: '8', value: 8 },
        { key: '9', value: 9 },
        { key: '0', value: 0 },
        { key: 'Minus', value: '-' },
        { key: 'Equal', value: '=' },
        { key: 'Backspace', value: 'Backspace', class: 'keyboard__key--grow' },
    ],
    [
        { key: 'Tab', value: 'Tab', class: 'keyboard__key--grow' },
        { key: 'q', value: 'q', valueUpper: 'Q' },
        { key: 'w', value: 'w', valueUpper: 'W' },
        { key: 'e', value: 'e', valueUpper: 'E' },
        { key: 'r', value: 'r', valueUpper: 'R' },
        { key: 't', value: 't', valueUpper: 'T' },
        { key: 'y', value: 'y', valueUpper: 'Y' },
        { key: 'u', value: 'u', valueUpper: 'U' },
        { key: 'i', value: 'i', valueUpper: 'I' },
        { key: 'o', value: 'o', valueUpper: 'O' },
        { key: 'p', value: 'p', valueUpper: 'P' },
        { key: 'BracketLeft', value: '[' },
        { key: 'BracketRight', value: ']' },
        { key: 'Backslash', value: '\\' },
        { key: 'Delete', value: 'Del', class: 'keyboard__key--grow' },
    ],
    [
        { key: 'CapsLock', value: 'CapsLock', class: 'keyboard__key--grow' },
        { key: 'a', value: 'a', valueUpper: 'A' },
        { key: 's', value: 's', valueUpper: 'S' },
        { key: 'd', value: 'd', valueUpper: 'D' },
        { key: 'f', value: 'f', valueUpper: 'F' },
        { key: 'g', value: 'g', valueUpper: 'G' },
        { key: 'h', value: 'h', valueUpper: 'H' },
        { key: 'j', value: 'j', valueUpper: 'J' },
        { key: 'k', value: 'k', valueUpper: 'K' },
        { key: 'l', value: 'l', valueUpper: 'L' },
        { key: 'Semicolon', value: ';' },
        { key: 'Quote', value: "'" },
        { key: 'Enter', value: 'Enter', class: 'keyboard__key--grow' },
    ],
    [
        { key: 'ShiftLeft', value: 'Shift', class: 'keyboard__key--grow' },
        { key: 'z', value: 'z', valueUpper: 'Z' },
        { key: 'x', value: 'x', valueUpper: 'X' },
        { key: 'c', value: 'c', valueUpper: 'C' },
        { key: 'v', value: 'v', valueUpper: 'V' },
        { key: 'b', value: 'b', valueUpper: 'B' },
        { key: 'n', value: 'n', valueUpper: 'N' },
        { key: 'm', value: 'm', valueUpper: 'M' },
        { key: 'Comma', value: ',' },
        { key: 'Period', value: '.' },
        { key: 'Slash', value: '/' },
        { key: 'ArrowUp', value: '▲' },
        { key: 'ShiftRight', value: 'Shift', class: 'keyboard__key--grow' },
    ],
    [
        { key: 'ControlLeft', value: 'Ctrl', class: 'keyboard__key--grow' },
        { key: 'MetaLeft', value: 'Win' },
        { key: 'AltLeft', value: 'Alt' },
        { key: 'Space', value: ' ', class: 'keyboard__key--space' },
        { key: 'AltRight', value: 'Alt' },
        { key: 'ArrowLeft', value: '◄' },
        { key: 'ArrowDown', value: '▼' },
        { key: 'ArrowRight', value: '►' },
        { key: 'ControlRight', value: 'Ctrl', class: 'keyboard__key--grow' },
    ]
]


export { keysColl }