const keysColl = [
    [
        { key: 'Backquote', value: '`' },
        { key: '1', value: 1 },
        { key: '2', value: 2 },
        { key: '3', value: 3 },
        { key: '4', value: 4 },
        { key: '5', value: 5 },
        { key: '6', value: 6 },
        { key: '7', value: 7 },
        { key: '8', value: 8 },
        { key: '9', value: 9 },
        { key: '0', value: 0 },
        { key: 'Minus', value: '-' },
        { key: 'Equal', value: '=' },
        { key: 'Backspace', value: 'Backspace', class: 'keyboard__key--grow' },
    ],
    [
        { key: 'Tab', value: 'Tab', class: 'keyboard__key--grow' },
        { key: 'q', value: 'q' },
        { key: 'w', value: 'w' },
        { key: 'e', value: 'e' },
        { key: 'r', value: 'r' },
        { key: 't', value: 't' },
        { key: 'y', value: 'y' },
        { key: 'u', value: 'u' },
        { key: 'i', value: 'i' },
        { key: 'o', value: 'o' },
        { key: 'p', value: 'p' },
        { key: 'BracketLeft', value: '[' },
        { key: 'BracketRight', value: ']' },
        { key: 'Backslash', value: '\\' },
        { key: 'Delete', value: 'Del', class: 'keyboard__key--grow' },
    ],
    [
        { key: 'CapsLock', value: 'CapsLock', class: 'keyboard__key--grow' },
        { key: 'a', value: 'a' },
        { key: 's', value: 's' },
        { key: 'd', value: 'd' },
        { key: 'f', value: 'f' },
        { key: 'g', value: 'g' },
        { key: 'h', value: 'h' },
        { key: 'j', value: 'j' },
        { key: 'k', value: 'k' },
        { key: 'l', value: 'l' },
        { key: 'Semicolon', value: ';' },
        { key: 'Quote', value: "'" },
        { key: 'Enter', value: 'Enter', class: 'keyboard__key--grow' },
    ],
    [
        { key: 'ShiftLeft', value: 'Shift', class: 'keyboard__key--grow' },
        { key: 'z', value: 'z' },
        { key: 'x', value: 'x' },
        { key: 'c', value: 'c' },
        { key: 'v', value: 'v' },
        { key: 'b', value: 'b' },
        { key: 'n', value: 'n' },
        { key: 'm', value: 'm' },
        { key: 'Comma', value: ',' },
        { key: 'Period', value: '.' },
        { key: 'Slash', value: '/' },
        { key: 'ArrowUp', value: '▲' },
        { key: 'ShiftRight', value: 'Shift', class: 'keyboard__key--grow' },
    ],
    [
        { key: 'ControlLeft', value: 'Ctrl', class: 'keyboard__key--grow' },
        { key: 'MetaLeft', value: 'Win' },
        { key: 'AltLeft', value: 'Alt' },
        { key: 'Space', value: ' ', class: 'keyboard__key--space' },
        { key: 'AltRight', value: 'Alt' },
        { key: 'ArrowLeft', value: '◄' },
        { key: 'ArrowDown', value: '▼' },
        { key: 'ArrowRight', value: '►' },
        { key: 'ControlRight', value: 'Ctrl', class: 'keyboard__key--grow' },
    ]
]

export { keysColl }